export const data = [
  {
    id: 1,
    poster: new URL("../assets/img/1.png", import.meta.url).href,
    alt: "video-1",
    ariaLabel: "Play video 1",
    title: "Soukromý dům v Rakousku · 800 m²",
    description: "Kompletní rekonstrukce",
    video: new URL("../assets/video/1new.mp4", import.meta.url).href,
  },
  {
    id: 2,
    poster: new URL("../assets/img/2.png", import.meta.url).href,
    alt: "video-2",
    ariaLabel: "Play video 2",
    title: "LOŽNICE 19 M² A OBÝVACÍ POKOJ 28 M²",
    description: "Individuální návrh interiéru",
    video: new URL("../assets/video/2new.mp4", import.meta.url).href,
  },
  {
    id: 3,
    poster: new URL("../assets/img/3.png", import.meta.url).href,
    alt: "video-3",
    ariaLabel: "Play video 3",
    title: "BYT 1,5+KK · 48 M²",
    description: "Rekonstrukce",
    video: new URL("../assets/video/3new.mp4", import.meta.url).href,
  },
  {
    id: 4,
    poster: new URL("../assets/img/4.png", import.meta.url).href,
    alt: "project-1",
    ariaLabel: "Open project 1",
    title: "TŘÍPOKOJOVÝ BYT · 70 m²",
    description: "Kompletní rekonstrukce",
    link: "https://www.youtube.com/shorts/4HZyKUMSFOU",

    target: "_blank",
  },
  {
    id: 5,
    poster: new URL("../assets/img/5.png", import.meta.url).href,
    alt: "project-2",
    ariaLabel: "Open project 2",
    title: "Třípokojový byt · 70 m²",
    description: "Kompletní rekonstrukce",
    link: "https://www.instagram.com/p/DKKYm8OK4vv/",

    target: "_blank",
  },
  {
    id: 6,
    poster: new URL("../assets/img/6.png", import.meta.url).href,
    alt: "project-3",
    ariaLabel: "Open project 3",
    title: "BYT 1+KK · 58 M²",
    description: "Návrh a finální realizace",
    link: new URL("../assets/video/ext.mp4", import.meta.url).href,
    target: "_blank",
  },
];
