export const data = [
  {
    id: 1,
    poster: "/public/img/1.png",
    alt: "video-1",
    ariaLabel: "Play video 1",
    title: "Soukromý dům v Rakousku · 800 m²",
    description: "Kompletní rekonstrukce",
    video: "/public/video/1new.mp4",
  },
  {
    id: 2,
    poster: "/public/img/2.png",
    alt: "video-2",
    ariaLabel: "Play video 2",
    title: "LOŽNICE 19 M² A OBÝVACÍ POKOJ 28 M²",
    description: "Individuální návrh interiéru",
    video: "/public/video/1new.mp4",
  },
  {
    id: 3,
    poster: "/public/img/3.png",
    alt: "video-3",
    ariaLabel: "Play video 3",
    title: "BYT 1,5+KK · 48 M²",
    description: "Rekonstrukce",
    video: "/public/video/1new.mp4",
  },
  {
    id: 4,
    poster: "/public/img/4.png",
    alt: "project-1",
    ariaLabel: "Open project 1",
    title: "TŘÍPOKOJOVÝ BYT · 70 m²",
    description: "Kompletní rekonstrukce",
    link: "https://www.youtube.com/shorts/4HZyKUMSFOU",
    linkText: "Zobrazit realizaci",
    target: "_blank",
  },
  {
    id: 5,
    poster: "/public/img/5.png",
    alt: "project-2",
    ariaLabel: "Open project 2",
    title: "Třípokojový byt · 70 m²",
    description: "Kompletní rekonstrukce",
    link: "https://www.instagram.com/p/DKKYm8OK4vv/",
    linkText: "Zobrazit realizaci",
    target: "_blank",
  },
  {
    id: 6,
    poster: "/public/img/6.png",
    alt: "project-3",
    ariaLabel: "Open project 3",
    title: "BYT 1+KK · 58 M²",
    description: "Návrh a finální realizace",
    link: "/video/project3.mp4",
    linkText: "Zobrazit realizaci",
    target: "_blank",
  },
];
